name: Deploy Python Web App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Upload to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "search-demo-webapp"
        package: "./app"
      env:
        AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
